version: '2'
services:
  mongodb:
    image: mongo:3.4
    hostname: mongodb
    ports:
      - 27017:27017
  initiatives-ideas:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    image: ${REPO}/ssg/initiatives_backend_ideas:${TAG_INITIATIVES_BACKEND}
    ports:
      - 8080:8080
    links:
      - mongodb
